// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu0jOAeckK6nXy49rAKX4YSX62zaXdESw',
    appId: '1:507486938861:web:0e7db76ad713acd9540ee4',
    messagingSenderId: '507486938861',
    projectId: 'tornamenttt',
    authDomain: 'tornamenttt.firebaseapp.com',
    storageBucket: 'tornamenttt.appspot.com',
    measurementId: 'G-R52F3MNLQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoiVhmXnRiF3BJ1bSoFL8MtWnhNKodK1Y',
    appId: '1:507486938861:android:1ebd78d6733c86d3540ee4',
    messagingSenderId: '507486938861',
    projectId: 'tornamenttt',
    storageBucket: 'tornamenttt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsQg0NYjyk49LIsliR_5gUb0Vr6RE0NdY',
    appId: '1:507486938861:ios:bd81e71ee2a119a2540ee4',
    messagingSenderId: '507486938861',
    projectId: 'tornamenttt',
    storageBucket: 'tornamenttt.appspot.com',
    iosBundleId: 'com.example.tornamenttabletennis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsQg0NYjyk49LIsliR_5gUb0Vr6RE0NdY',
    appId: '1:507486938861:ios:bd81e71ee2a119a2540ee4',
    messagingSenderId: '507486938861',
    projectId: 'tornamenttt',
    storageBucket: 'tornamenttt.appspot.com',
    iosBundleId: 'com.example.tornamenttabletennis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu0jOAeckK6nXy49rAKX4YSX62zaXdESw',
    appId: '1:507486938861:web:e56aa90e539bd410540ee4',
    messagingSenderId: '507486938861',
    projectId: 'tornamenttt',
    authDomain: 'tornamenttt.firebaseapp.com',
    storageBucket: 'tornamenttt.appspot.com',
    measurementId: 'G-ZSX3DDV2Q1',
  );
}
